"""Canonical event type names."""

CAPTURE_RECEIVED = "capture.received"
CAPTURE_CLASSIFIED = "capture.classified"
AGENT_RUN_STARTED = "agent.run_started"
AGENT_STATUS_UPDATED = "agent.status_updated"
AGENT_HANDOFF_CREATED = "agent.handoff_created"
PROVIDER_CALL_STARTED = "provider.call_started"
PROVIDER_CALL_FAILED = "provider.call_failed"
PROVIDER_FALLBACK_USED = "provider.fallback_used"
TOOL_REQUESTED = "tool.requested"
TOOL_APPROVAL_REQUIRED = "tool.approval_required"
TOOL_STARTED = "tool.started"
TOOL_SUCCEEDED = "tool.succeeded"
TOOL_FAILED = "tool.failed"
REVIEW_CREATED = "review.created"
REVIEW_SURFACED_DISCORD = "review.surfaced_discord"
REVIEW_DECISION_RECEIVED = "review.decision_received"
STATE_CHANGE_APPLIED = "state_change.applied"
MEMORY_CANDIDATE_CREATED = "memory.candidate_created"
MEMORY_FACT_APPROVED = "memory.fact_approved"
JOB_STARTED = "job.started"
JOB_FAILED = "job.failed"
NOTIFICATION_SENT = "notification.sent"
NOTIFICATION_FAILED = "notification.failed"
